### ISSUE TITLE
Erro ao subir o servidor

### ISSUE THREAD

**Issue by williansmartins** [douglaspands/core-graphql-js#1]
Olá Douglas, um colega seu da GFT me indicou este projeto, estou tentando subir o projeto, mas esta dando o erro seguinte, pode dar um help?

Executei os comando descritos no readme:
`npm install`
e
`npm run start-dev`

Não vi como fazer a parte:
` iniciar o servidor com o comando (NODE_ENV != 'production'):`

`Erro no registro da API GraphQL:
-> Function Resolved.: .\apps\graphql-funcionarios\index.js
-> GraphQL Schema....: .\apps\graphql-funcionarios\funcionarios.gql
-> Function Resolved.: .\apps\graphql-usuarios\index.js
-> GraphQL Schema....: .\apps\graphql-usuarios\usuarios.gql
C:\dev\projetos\pwms\core-graphql-js\src\node_modules\mongodb\lib\mongo_client.js:433
          throw err
          ^

Error: Specified query type "Query" not found in document.
    at C:\dev\projetos\pwms\core-graphql-js\src\node_modules\graphql\utilities\buildASTSchema.js:133:17
    at Array.forEach (native)
    at buildASTSchema (C:\dev\projetos\pwms\core-graphql-js\src\node_modules\graphql\utilities\buildASTSchema.js:126:30)
    at buildSchema (C:\dev\projetos\pwms\core-graphql-js\src\node_modules\graphql\utilities\buildASTSchema.js:456:10)
    at module.exports.server (C:\dev\projetos\pwms\core-graphql-js\src\lib\scan-apps-graphql\index.js:83:17)
    at async.auto.graphql (C:\dev\projetos\pwms\core-graphql-js\src\server.js:39:64)
    at runTask (C:\dev\projetos\pwms\core-graphql-js\src\node_modules\async\dist\async.js:1618:13)
    at C:\dev\projetos\pwms\core-graphql-js\src\node_modules\async\dist\async.js:1558:13
    at processQueue (C:\dev\projetos\pwms\core-graphql-js\src\node_modules\async\dist\async.js:1568:13)
    at taskComplete (C:\dev\projetos\pwms\core-graphql-js\src\node_modules\async\dist\async.js:1587:9)
`

**Comment by williansmartins** [comment]
Percebi que a versão do node que eu estava usando era a 6, subi para a 8.9.1 e agora esta subindo, agora estou tentando rodar uma querie, mas sem sucesso(falta de conhecimento mesmo, kkk)
